services:
  - type: web
    name: weatherapp
    runtime: python

    buildCommand: "./build.sh"

    startCommand: "gunicorn weatherproject.wsgi:application"

    envVars:
      - key: DEBUG
        value: False

      - key: SECRET_KEY
        generateValue: true

      - key: OPENWEATHER_API_KEY
        sync: false